

package com.github.kantis.mikrom.plugin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.github.kantis.mikrom.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("mikrom-compiler-plugin/testData/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("mikrom-compiler-plugin/testData/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Person.kt")
  public void testPerson() {
    runTest("mikrom-compiler-plugin/testData/diagnostic/Person.kt");
  }
}
