package io.github.kantis.mikrom.generator

import io.github.kantis.mikrom.MikromInternal
import io.github.kantis.mikrom.RowMapper

/**
 * An interface for a [io.github.kantis.mikrom.RowMapper] instance generated by the compiler plugin.
 *
 * Should not be implemented manually or used directly.
 */
@MikromInternal
public interface GeneratedRowMapper<out T> : RowMapper<T>
